import selenium
from selenium import webdriver
import time
from datetime import datetime, timedelta
import os
import smtplib


chrome_options = webdriver.ChromeOptions()
chrome_options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), chrome_options=chrome_options)


# Now you can start using Selenium
while(True):
  driver.get ('https://my.te.eg/#/home/signin')
  print(driver.title)

  time.sleep(3)
  driver.find_element_by_id('MobileNumberID').send_keys(os.environ.get("heroku_var_WENum"))
  time.sleep(1)
  driver.find_element_by_id ('PasswordID').send_keys(os.environ.get("heroku_var_WEpass"))
  time.sleep(1)
  driver.find_element_by_id('singInBtn').click()
  time.sleep(4)


  # login successful
  print(driver.title)

  # getting remainning GB
  array=driver.find_elements_by_css_selector('tspan')
  GB=float(array[3].text)
  time.sleep(4)

  #اضغط ع تفاصيل الاستهلاك
  driver.find_element_by_css_selector('button.btn.btn-primary').click()
  time.sleep(3)
  print(driver.title)



  #get_attribute("value")
  # تاريخ الشحن ك نص
  date_text= driver.find_element_by_css_selector('div.col-sm-6').text
  # تحويل النص لتاريخ
  date_formatted = datetime.strptime(date_text,"%Y-%m-%d")
  #get current date and time
  now = datetime.now()
  difference = now-date_formatted
  #الايام المتبقية
  days=30-difference.days
  # معدل الاستهلاك ... المعدل الطبيعي 250/30 = 8.33 جيجا في اليوم
  rate=GB/days
  #print("%.2f" % rate)
  time.sleep(5)

  # Sending email

  server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
  
  # you need to trun on 2FA on the sender email, and then get an app password (goole that if u don't know ehat i'm taking about)
  server.login(os.environ.get("heroku_var_sndrEmail"), os.environ.get("heroku_var_2FApass"))

  rate = str(round(rate, 2))
  print(rate)
  date = date_formatted + timedelta(30)
  date = date.strftime("%d/%m/%Y")
  rate_str = '#Rate: ' + str(rate) + ' GB'
  days_str = '#Remaining: ' +str(GB)+ ' GB & '+ str(days) + ' days'
  date_str = '#You have to recharge before: ' + str(date)

  subject = 'WE Internet Consumption'
  body = rate_str + '\n\n' + days_str + '\n\n' + date_str
  msg = f'Subject: {subject}\n\n{body}'

  server.sendmail(os.environ.get("heroku_var_sndrEmail"), os.environ.get("heroku_var_rcvrEmail"), msg)

  print('\n### Email was sent successfully! ###')
  server.quit()


  
  # Wasting time 1728*100 = 48 hours
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)
  driver.get ('https://dogehouse.tv')
  time.sleep(1728)

#driver.quit()
